
[build]
target = "i386-unknown-none.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]


[target.x86]
runner = "scripts/qemu.sh"

[target.x86_64]
runner = "scripts/qemu.sh"

[target.i386-unknown-none]
runner = "scripts/qemu.sh"
rustflags = [
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-static",
    "-C", "relocation-model=static",
    "-C", "code-model=kernel",
]
